epde_params = {
    'burg': {'boundary': 10,
             'population_size': 5,
             'training_epochs': 5,
             'max_deriv_order': (1, 1),
             'equation_terms_max_number': 3,
             'equation_factors_max_number': 2,
             'eq_sparsity_interval': (1e-08, 1e-4),
             'num': 4},

    'burg_sindy': {'boundary': 10,
                   'population_size': 8,
                   'training_epochs': 7,
                   'max_deriv_order': (1, 2),
                   'equation_terms_max_number': 3,
                   'equation_factors_max_number': 2,
                   'eq_sparsity_interval': (1e-08, 1e-1),
                   'num': 4},

    'kdv': {'boundary': 0,
            'population_size': 8,
            'training_epochs': 90,
            'max_deriv_order': (1, 3),
            'equation_terms_max_number': 4,
            'equation_factors_max_number': 2,
            'eq_sparsity_interval': (1e-08, 1e-06),
            'num': 2},

    'kdv_sindy': {'boundary': 0,
                  'population_size': 8,
                  'training_epochs': 90,
                  'max_deriv_order': (1, 3),
                  'equation_terms_max_number': 4,
                  'equation_factors_max_number': 2,
                  'eq_sparsity_interval': (1e-08, 1e-06),
                  'num': 4},

    'wave': {'bnd': 10,
             'population_size': 5,
             'training_epochs': 5,
             'max_deriv_order': (2, 2),
             'equation_terms_max_number': 3,
             'equation_factors_max_number': 1,
             'eq_sparsity_interval': (1e-08, 5),
             'num': 2},
}